package visao;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Livro;

/**
 *
 * @author UdsonWillams
 */
public class AlugarLivro extends javax.swing.JFrame {
    
    ArrayList<Livro> livros = new ArrayList<Livro>();
    
        Livro biblia = new Livro("a biblia", "eletronico", "JC", "N sei", 2000, 0);
        Livro matematica = new Livro("naruto", "fisico", "udson", "N sei", 1990, 5);
        Livro ingles = new Livro("o ingles", "fisico", "joao", "N sei", 2010, 3);
              
    
    public AlugarLivro() {
        
        livros.add(biblia);
        livros.add(matematica);
        livros.add(ingles); 
        boolean validador;
        
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        nomeLivro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aluguelNomeUsario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Aluguel de Livros");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        nomeLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeLivroActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do Livro: ");

        jLabel2.setText("Nome do Usario:");

        aluguelNomeUsario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aluguelNomeUsarioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Morais Library");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aluguelNomeUsario, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(nomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(aluguelNomeUsario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeLivroActionPerformed
                  
        boolean validador = false;
        int tamanhoLivros = livros.size();
        int i = 0;
        Livro teste = new Livro();
        
        if (nomeLivro.getText().equals("") && aluguelNomeUsario.getText() == ""){
            JOptionPane.showMessageDialog(null,"DIGITE VALORES VALIDOS");
        }
        else if (i == 2 && validador == true){
                    JOptionPane.showMessageDialog(null,"LIVRO NÃO ENCONTRADO");
        }                    
        else{                   
            for (i = 0; i < tamanhoLivros; i++){

                teste = livros.get(i);                        
                               
                if (nomeLivro.getText().equals(teste.getNomeDoLivro())){
                    validador = true;
                    int quantidade = teste.getQuantidadeLivros();

                    if (teste.getTipoDoLivro().equals("digital")){
                        JOptionPane.showMessageDialog(null,"LIVRO DIGITAL, NAO PODE SER ALUGADO");
                    } 

                    else if (teste.getTipoDoLivro().equals("fisico") && quantidade > 0 && aluguelNomeUsario.getText() != ""){
                        int novaQuantidade = teste.getQuantidadeLivros() - 1;
                        teste.setQuantidadeLivros(novaQuantidade);                    
                        if (quantidade > 1){
                            if (aluguelNomeUsario.getText().toUpperCase().equals("PROFESSOR")){
                                JOptionPane.showMessageDialog(null,"LIVRO ALUGADO PARA " + aluguelNomeUsario.getText().toUpperCase() + " POR 10 DIAS");
                            }
                            else if (aluguelNomeUsario.getText().toUpperCase().equals("PROFESSORA")){
                                JOptionPane.showMessageDialog(null,"LIVRO ALUGADO PARA " + aluguelNomeUsario.getText().toUpperCase() + " POR 10 DIAS");
                            }
                            else {
                                JOptionPane.showMessageDialog(null,"LIVRO ALUGADO PARA " + aluguelNomeUsario.getText().toUpperCase() + " POR 7 DIAS");
                            }
                        }
                        else {
                            JOptionPane.showMessageDialog(null,"ULTIMO EXEMPLAR DA BIBLIOTECA ALUGADO PARA " + aluguelNomeUsario.getText().toUpperCase() + " POR 3 DIAS");
                        }                  
                    }
                    else if (teste.getTipoDoLivro().equals("fisico") && quantidade > 0 ){
                        JOptionPane.showMessageDialog(null,"DIGITE VALORES VALIDOS"); 
                    }
                    else {
                        JOptionPane.showMessageDialog(null,"LIVRO ESGOTADO");
                        validador = false;
                    }                
                }
                
            }                        
        }
    }//GEN-LAST:event_nomeLivroActionPerformed

    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
            
    }//GEN-LAST:event_formComponentShown

    private void aluguelNomeUsarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aluguelNomeUsarioActionPerformed
        
    }//GEN-LAST:event_aluguelNomeUsarioActionPerformed

    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlugarLivro().setVisible(true);
            }

        });
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aluguelNomeUsario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField nomeLivro;
    // End of variables declaration//GEN-END:variables
}
