/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import visao.eventos.CadEvento;

/**
 *
 * @author Leo
 */
public class TelaEvento extends javax.swing.JFrame {

    /**
     * Creates new form Eventos
     */
    public TelaEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuEvento = new javax.swing.JMenu();
        jMenuItemCadEv = new javax.swing.JMenuItem();
        jMenuItemVerifEv = new javax.swing.JMenuItem();
        jMenuItemImpEv = new javax.swing.JMenuItem();
        jMenuItemExcEv = new javax.swing.JMenuItem();
        jMenuEspaço = new javax.swing.JMenu();
        jMenuItemCadEsp = new javax.swing.JMenuItem();
        jMenuItemResEsp = new javax.swing.JMenuItem();
        jMenuItemChkEsp = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSairMenu = new javax.swing.JMenuItem();
        jMenuItemSairUser = new javax.swing.JMenuItem();
        jMenuItemSairGeral = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 450));
        setSize(new java.awt.Dimension(600, 450));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UNIESP_LOGO.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -110, 600, 600);

        jMenuEvento.setText("Eventos");

        jMenuItemCadEv.setText("Cadastrar Eventos");
        jMenuItemCadEv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadEvActionPerformed(evt);
            }
        });
        jMenuEvento.add(jMenuItemCadEv);

        jMenuItemVerifEv.setText("Verificar Eventos");
        jMenuEvento.add(jMenuItemVerifEv);

        jMenuItemImpEv.setText("Importar Evento");
        jMenuEvento.add(jMenuItemImpEv);

        jMenuItemExcEv.setText("Excluir Evento");
        jMenuEvento.add(jMenuItemExcEv);

        jMenuBar1.add(jMenuEvento);

        jMenuEspaço.setText("Espaços");

        jMenuItemCadEsp.setText("Cadastrar Espaço");
        jMenuEspaço.add(jMenuItemCadEsp);

        jMenuItemResEsp.setText("Reservar Espaço");
        jMenuEspaço.add(jMenuItemResEsp);

        jMenuItemChkEsp.setText("Checar Espaço");
        jMenuEspaço.add(jMenuItemChkEsp);

        jMenuBar1.add(jMenuEspaço);

        jMenuSair.setText("Sair");

        jMenuItemSairMenu.setText("Menu Principal");
        jMenuItemSairMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairMenuActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSairMenu);

        jMenuItemSairUser.setText("Sair do Usuário");
        jMenuItemSairUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairUserActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSairUser);

        jMenuItemSairGeral.setText("Fechar Sistema");
        jMenuItemSairGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairGeralActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSairGeral);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(616, 490));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairGeralActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairGeralActionPerformed

    private void jMenuItemSairMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairMenuActionPerformed
        TelaPrincipalAdmin tela = new TelaPrincipalAdmin();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemSairMenuActionPerformed

    private void jMenuItemSairUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairUserActionPerformed
        /*TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        dispose();
        */
    }//GEN-LAST:event_jMenuItemSairUserActionPerformed

    private void jMenuItemCadEvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadEvActionPerformed
        CadEvento cadEvento = new CadEvento();
        cadEvento.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadEvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEspaço;
    private javax.swing.JMenu jMenuEvento;
    private javax.swing.JMenuItem jMenuItemCadEsp;
    private javax.swing.JMenuItem jMenuItemCadEv;
    private javax.swing.JMenuItem jMenuItemChkEsp;
    private javax.swing.JMenuItem jMenuItemExcEv;
    private javax.swing.JMenuItem jMenuItemImpEv;
    private javax.swing.JMenuItem jMenuItemResEsp;
    private javax.swing.JMenuItem jMenuItemSairGeral;
    private javax.swing.JMenuItem jMenuItemSairMenu;
    private javax.swing.JMenuItem jMenuItemSairUser;
    private javax.swing.JMenuItem jMenuItemVerifEv;
    private javax.swing.JMenu jMenuSair;
    // End of variables declaration//GEN-END:variables
}
