/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import visao.eventos.*;

/**
 *
 * @author Leo
 */
public class TelaEvento extends javax.swing.JFrame {

    /**
     * Creates new form Eventos
     */
    public TelaEvento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jBtEventos = new javax.swing.JButton();
        jBtImportarEvento = new javax.swing.JButton();
        jBtEspacos = new javax.swing.JButton();
        jBtSalaEstudo = new javax.swing.JButton();
        jBtVoltar = new javax.swing.JButton();
        jBtSair = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuEvento = new javax.swing.JMenu();
        jMenuItemListEven = new javax.swing.JMenuItem();
        jMenuItemImpEv = new javax.swing.JMenuItem();
        jMenuEspaço = new javax.swing.JMenu();
        jMenuItemListEsp = new javax.swing.JMenuItem();
        jMenuItemSalaEstudo = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSairMenu = new javax.swing.JMenuItem();
        jMenuItemSairUser = new javax.swing.JMenuItem();
        jMenuItemSairGeral = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca - Eventos e Espaços");
        setPreferredSize(new java.awt.Dimension(600, 450));
        setSize(new java.awt.Dimension(600, 450));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Sair");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 1510, 590, 49);

        jBtEventos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtEventos.setText("Lista de Eventos");
        jBtEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtEventosActionPerformed(evt);
            }
        });
        getContentPane().add(jBtEventos);
        jBtEventos.setBounds(10, 80, 130, 30);

        jBtImportarEvento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtImportarEvento.setText("Importar Evento");
        getContentPane().add(jBtImportarEvento);
        jBtImportarEvento.setBounds(10, 120, 130, 30);

        jBtEspacos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtEspacos.setText("Lista de Espaços");
        jBtEspacos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtEspacosActionPerformed(evt);
            }
        });
        getContentPane().add(jBtEspacos);
        jBtEspacos.setBounds(10, 160, 130, 30);

        jBtSalaEstudo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtSalaEstudo.setText("Sala de Estudos");
        jBtSalaEstudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSalaEstudoActionPerformed(evt);
            }
        });
        getContentPane().add(jBtSalaEstudo);
        jBtSalaEstudo.setBounds(10, 200, 130, 30);

        jBtVoltar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtVoltar.setText("Voltar");
        jBtVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtVoltar);
        jBtVoltar.setBounds(430, 350, 70, 23);

        jBtSair.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtSair.setText("Sair");
        jBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairActionPerformed(evt);
            }
        });
        getContentPane().add(jBtSair);
        jBtSair.setBounds(430, 380, 70, 23);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UNIESP_LOGO.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(-40, -100, 600, 600);

        jMenuEvento.setText("Eventos");

        jMenuItemListEven.setText("Lista de Eventos");
        jMenuItemListEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListEvenActionPerformed(evt);
            }
        });
        jMenuEvento.add(jMenuItemListEven);

        jMenuItemImpEv.setText("Importar Evento");
        jMenuEvento.add(jMenuItemImpEv);

        jMenuBar1.add(jMenuEvento);

        jMenuEspaço.setText("Espaços");

        jMenuItemListEsp.setText("Lista de Espaços");
        jMenuItemListEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListEspActionPerformed(evt);
            }
        });
        jMenuEspaço.add(jMenuItemListEsp);

        jMenuItemSalaEstudo.setText("Sala de Estudos");
        jMenuItemSalaEstudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalaEstudoActionPerformed(evt);
            }
        });
        jMenuEspaço.add(jMenuItemSalaEstudo);

        jMenuBar1.add(jMenuEspaço);

        jMenuSair.setText("Sair");

        jMenuItemSairMenu.setText("Menu Principal");
        jMenuItemSairMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairMenuActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSairMenu);

        jMenuItemSairUser.setText("Sair do Usuário");
        jMenuItemSairUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairUserActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSairUser);

        jMenuItemSairGeral.setText("Fechar Sistema");
        jMenuItemSairGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairGeralActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSairGeral);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(529, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairGeralActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairGeralActionPerformed

    private void jMenuItemSairMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairMenuActionPerformed
        TelaPrincipalAdmin tela = new TelaPrincipalAdmin();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemSairMenuActionPerformed

    private void jMenuItemSairUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairUserActionPerformed
        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jMenuItemSairUserActionPerformed

    private void jMenuItemListEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListEspActionPerformed
        VisaoEspaco janela = new VisaoEspaco();
        janela.setVisible(true);
    }//GEN-LAST:event_jMenuItemListEspActionPerformed

    private void jBtEspacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtEspacosActionPerformed
        VisaoEspaco janela = new VisaoEspaco();
        janela.setVisible(true);
    }//GEN-LAST:event_jBtEspacosActionPerformed

    private void jBtVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtVoltarActionPerformed
        TelaPrincipalAdmin tela = new TelaPrincipalAdmin();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtVoltarActionPerformed

    private void jBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtSairActionPerformed

    private void jBtEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtEventosActionPerformed
        VisaoEvento tela = new VisaoEvento();
        tela.setVisible(true);
    }//GEN-LAST:event_jBtEventosActionPerformed

    private void jMenuItemListEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListEvenActionPerformed
        VisaoEvento tela = new VisaoEvento();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemListEvenActionPerformed

    private void jBtSalaEstudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSalaEstudoActionPerformed
        VisaoSalaEstudo tela = new VisaoSalaEstudo();
        tela.setVisible(true);
    }//GEN-LAST:event_jBtSalaEstudoActionPerformed

    private void jMenuItemSalaEstudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalaEstudoActionPerformed
        VisaoSalaEstudo tela = new VisaoSalaEstudo();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItemSalaEstudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtEspacos;
    private javax.swing.JButton jBtEventos;
    private javax.swing.JButton jBtImportarEvento;
    private javax.swing.JButton jBtSair;
    private javax.swing.JButton jBtSalaEstudo;
    private javax.swing.JButton jBtVoltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEspaço;
    private javax.swing.JMenu jMenuEvento;
    private javax.swing.JMenuItem jMenuItemImpEv;
    private javax.swing.JMenuItem jMenuItemListEsp;
    private javax.swing.JMenuItem jMenuItemListEven;
    private javax.swing.JMenuItem jMenuItemSairGeral;
    private javax.swing.JMenuItem jMenuItemSairMenu;
    private javax.swing.JMenuItem jMenuItemSairUser;
    private javax.swing.JMenuItem jMenuItemSalaEstudo;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
